UPDATE [dbo].[PLAYER] SET [POSITION] = 'C' WHERE [POSITION] = 'Center';
UPDATE [dbo].[PLAYER] SET [POSITION] = 'RW' WHERE [POSITION] = 'Right Wing';
UPDATE [dbo].[PLAYER] SET [POSITION] = 'LW' WHERE [POSITION] = 'Left Wing';
UPDATE [dbo].[PLAYER] SET [POSITION] = 'LW' WHERE [POSITION] = 'Defenseman';
UPDATE [dbo].[PLAYER] SET [POSITION] = 'G' WHERE [POSITION] = 'Goalie';